foundry_user: foundry
foundry_group: foundry
foundry_dir: /usr/local/foundry-vtt
foundry_file:
foundry_domain:
foundry_key:
foundry_port: 30000
foundry_service_name: foundryvtt

foundry_backup_user: foundry_backup
foundry_backup_tool_path: /usr/local/spacesbackup
foundry_backup_space:
foundry_backup_region:
foundry_backup_url:
foundry_backup_space_key:
foundry_backup_space_secret:
foundry_backup_path: foundry
foundry_backup_file: spacesbackup.ini
foundry_backup_service_name: spacesbackup
